name: Custom CASD Trevas Lab

on:
  workflow_dispatch:
    inputs:
      api_version:
        description: "Trevas Lab version"
        required: true
        default: "0.5.1"
        type: choice
        options:
          - 0.5.1
      ui_version:
        description: "Trevas Lab UI version"
        required: true
        default: "0.7.2"
        type: choice
        options:
          - 0.7.2
      spark_properties:
        description: 'Spark engine properties (SPARk_KEY=value, no whitespace, "," separator)'
        required: false
        default: ""
        type: string

jobs:
  trevas-lab:
    name: Build Trevas Lab
    runs-on: ubuntu-latest
    steps:
      - name: Clone Trevas Lab repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.api_version }}
          repository: InseeFrLab/Trevas-Lab
          path: trevas-lab
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]
      - name: Build with Maven
        run: |
          spark_properties="${{ inputs.spark_properties }}"

          # Split the input string into a list of strings
          spark_properties_list=(${spark_properties//,/ })

          ARGS=""

          # Iterate over the list of strings
          for item in "${spark_properties_list[@]}"
          do
            ARGS="$ARGS -D$item"
          done
          echo "Args: $ARGS"
          mvn -B clean package war:war -DskipTests $ARGS
        working-directory: "./trevas-lab"
      - run: mkdir war
        working-directory: "./trevas-lab/target"
      - run: cp ./trevas-lab/target/trevas-lab-*.war ./trevas-lab/target/war/trevas-lab-${{ inputs.api_version }}.war
      - name: Upload Trevas Lab into trevas-lab archive
        uses: actions/upload-artifact@v4
        with:
          name: trevas-lab-${{ inputs.api_version }}
          path: trevas-lab/target/war

  trevas-lab-ui:
    name: Build Trevas Lab UI
    runs-on: ubuntu-latest
    steps:
      - name: Clone Livrables CASD repository
        uses: actions/checkout@v4
      - name: Clone Trevas Lab UI repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.ui_version }}
          repository: InseeFrLab/Trevas-Lab-UI
          path: trevas-lab-ui
      - uses: actions/setup-node@v4
        with:
          node-version: 16.19.0
      - name: Build
        run: |
          yarn
          yarn build
          REACT_APP_API_BASE_URL="http://localhost:8080" REACT_APP_MODULES=in-memory,spark REACT_APP_FILE_PATH_LOCATION=LOCAL npx embed-environnement-variables
        working-directory: "./trevas-lab-ui"
      - run: cp ./trevas-lab-ui-config/web.config ./trevas-lab-ui/build/web.config
      - name: Upload Trevas Lab UI artifact
        uses: actions/upload-artifact@v4
        with:
          name: trevas-lab-ui-${{ inputs.ui_version }}
          path: trevas-lab-ui/build
