name: Custom CASD Trevas Lab

on:
  workflow_dispatch:
    inputs:
      api_version:
        description: "Trevas Lab version"
        required: true
        default: "0.1.0"
        type: choice
        options:
          - 0.1.0
          - master
      ui_version:
        description: "Trevas Lab UI version"
        required: true
        default: "0.5.0"
        type: choice
        options:
          - 0.5.0
          - master

jobs:
  trevas-lab:
    name: Build Trevas Lab
    runs-on: ubuntu-latest
    steps:
      - name: Clone Trevas Lab repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ inputs.api_version }}
          repository: InseeFrLab/Trevas-Lab
          path: trevas-lab
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]
      - name: Build with Maven
        run: mvn -B clean package war:war -DskipTests
        working-directory: "./trevas-lab"
      - run: mkdir war
        working-directory: "./trevas-lab/target"
      - run: cp ./trevas-lab/target/trevas-lab-*.war ./trevas-lab/target/war/trevas-lab.war
      - name: Upload Trevas Lab into trevas-lab archive
        uses: actions/upload-artifact@master
        with:
          name: trevas-lab:${{ inputs.api_version }}
          path: trevas-lab/target/war

  trevas-lab-ui:
    name: Build Trevas Lab UI
    runs-on: ubuntu-latest
    steps:
      - name: Clone Livrables CASD repository
        uses: actions/checkout@v2
      - name: Clone Trevas Lab UI repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ inputs.ui_version }}
          repository: InseeFrLab/Trevas-Lab-UI
          path: trevas-lab-ui
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          yarn
          yarn build
          REACT_APP_API_BASE_URL="http://localhost:8080" REACT_APP_MODULES=in-memory,spark/local REACT_APP_FILE_PATH_LOCATION=LOCAL npx embed-environnement-variables
        working-directory: "./trevas-lab-ui"
      - run: cp ./trevas-lab-ui-config/web.config ./trevas-lab-ui/build/web.config
      - name: Upload Trevas Lab UI artifact
        uses: actions/upload-artifact@v2
        with:
          name: trevas-lab-ui:${{ inputs.ui_version }}
          path: trevas-lab-ui/build
