name: Custom CASD Trevas Jupyter

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Trevas Jupyter version"
        required: true
        default: "standalone-0.4.1"
        type: choice
        options:
          - standalone-0.4.1

jobs:
  trevas-jupyter:
    name: Build Trevas Jupyter
    runs-on: ubuntu-latest
    steps:
      - name: Clone Trevas Jupyter repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ inputs.version }}
          repository: Making-Sense-Info/Trevas-Jupyter
          path: trevas-jupyter
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        working-directory: "./trevas-jupyter"
      - run: cp ./trevas-jupyter/kernel-windows.json ./trevas-jupyter/target/appassembler/kernel.json
      - name: Upload Trevas Jupyter into trevas-jupyter archive
        uses: actions/upload-artifact@master
        with:
          name: trevas-jupyter-${{ inputs.version }}
          path: trevas-jupyter/target/appassembler
